# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 725d866f1d433e789719c7e007df36843ecdae3e4321ef144dcf36d146a9491eb63e1b60bf2ed666e89157d2c66350e65e98b958174a0cd57e11bc24d4c2583f

test:
  secret_key_base: 2f9133c782b97b16d463b24c6e0a84e95a13aa2e9303669a88464610a273b202d33f0c6732dc8a6d53d721168e1fae90cdb74994624f259cd2da6687859af270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
